### ISSUE TITLE
Error when running example in README

### ISSUE THREAD

**Issue by ksonbol** [ykzeng/emuedge#17]
Hello,

Running the example given in the README file gives this error:

> DEBUG:root:xen.py:385:__del__:in the destructor of xnet
> Exception AttributeError: "xen_net instance has no attribute 'router_set'" in <bound method xen_net.__del__ of <xen.xen_net instance at 0x7f570a224b00>> ignored
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "xen.py", line 430, in test_topo
>     xnet=xen_net("root", "789456123", tlst, dist_db=dist_db)
>   File "xen.py", line 44, in __init__
>     self.session=xen_net.init_session(uname, pwd)
>   File "xen.py", line 89, in init_session
>     session.xenapi.login_with_password(uname, pwd)
>   File "/home/karim/.local/lib/python2.7/site-packages/XenAPI/XenAPI.py", line 264, in __call__
>     return self.__send(self.__name, args)
>   File "/home/karim/.local/lib/python2.7/site-packages/XenAPI/XenAPI.py", line 151, in xenapi_request
>     self._login(methodname, params)
>   File "/home/karim/.local/lib/python2.7/site-packages/XenAPI/XenAPI.py", line 188, in _login
>     raise e
> socket.error: [Errno 2] No such file or directory

When I run: `xnet=xen.test_topo(topo='exps/twoway_simple.topo')
`

I created the file and checked its location, but the error seems to be related to the XenAPI library.

**Comment by ykzeng** [comment]
Hi ksonbol,

It seems to me that the error you are getting is because you are not running on Xen, the version of EmuEdge here is still heavily dependent on Xen. 

There are a handful of Xen versions that you can install before running EmuEdge. Please refer to `https://docs.citrix.com/en-us/xenserver/7-0.html` if you want to install XenServer (one of our recommended choice). After that you should be able to start EmuEdge.

Thanks, pls let me know if you have any other questions
Vincent

**Comment by ksonbol** [comment]
Hi @ykzeng,

Thank you for the quick response. I am afraid I am not so familiar with Xen. I did try to download the XenServer but links are locked for some reason. It says "requires additional permissions to access" on the [download site](https://www.citrix.com/downloads/citrix-hypervisor/). Only the [HyperVisor 8.0 Express Edition](https://www.citrix.com/downloads/citrix-hypervisor/product-software/hypervisor-80-express-edition.html) is available for download but it has limited features and I am guessing it may not work with EmuEdge? I have xen-hypervisor-amd64 installed but I don't really know how to use it with EmuEdge.

Also, is there another version of EmuEdge which does not depend on Xen?

Thanks.

**Comment by ykzeng** [comment]
hi @ksonbol 

I am not familiar with recent updates on XenServer too. Though, it seems HyperVisor is just a upgrade and rebranding of XenServer to me and it is likely that they provide backward compatibility, so you may still try HyperVisor (or other possible free XenServer versions) if you need EmuEdge in the short term. 

We do notice that EmuEdge will be more user-friendly if it supports more easier setup and less platform requirements. We are working on an alternative right now diligently to make our EmuEdge Cloud-compatible so that everyone can access it easily. If you will still be interested in long term, pls stay tuned by starring our project. We will announce when any new releases come out.

Once again, thank you so much for reaching out!

**Comment by ksonbol** [comment]
Thank you Yukun, looking forward to the new updates.

**Comment by ykzeng** [comment]
Closing this issue while we are still working on releasing a Cloud-based version of EmuEdge. Will be sending out notifications if any updates.

Yukun Zeng
